name: Workflow CI - Churn MLflow

on:
  push:
    branches:
      - main
    paths:
      - 'Workflow-CI/**'
  workflow_dispatch:
    inputs:
      n_estimators:
        description: 'Jumlah estimators RandomForest'
        required: false
        default: '100'
      max_depth:
        description: 'Max depth RandomForest (0 = None)'
        required: false
        default: '10'

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow dagshub pandas numpy matplotlib seaborn scikit-learn requests

      # Step 4: Jalankan MLflow Project (training)
      - name: Run MLflow Project Training
        env:
          MLFLOW_TRACKING_USERNAME: aadnauj
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow run Workflow-CI/MLProject \
            --env-manager=local \
            -P n_estimators=${{ github.event.inputs.n_estimators || '100' }} \
            -P max_depth=${{ github.event.inputs.max_depth || '10' }} \
            -P random_state=42 \
            -P test_size=0.2

      # Step 5: Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 6: Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 7: Build Docker Image menggunakan mlflow build-docker
      - name: Build Docker Image with MLflow
        run: |
          pip install mlflow
          mlflow models build-docker \
            --model-uri "models:/RandomForest_WorkflowCI/latest" \
            --name "aadnauj/workflow-ci:latest" \
            --env-manager=local
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/aadnauj/Eksperimen_SML_Juanda-Harefa.mlflow
          MLFLOW_TRACKING_USERNAME: aadnauj
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

      # Step 8: Push Docker Image ke Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push aadnauj/workflow-ci:latest
          docker tag aadnauj/workflow-ci:latest aadnauj/workflow-ci:${{ github.sha }}
          docker push aadnauj/workflow-ci:${{ github.sha }}

      # Step 9: Simpan artefak ke GitHub
      - name: Upload Training Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: training-artifacts-${{ github.sha }}
          path: |
            mlruns/
          retention-days: 30

